name: eduardvalentin/plone-backend
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image for ${{ matrix.platform }}
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            -t eduardvalentin/plone-backend:dev-${{ matrix.platform }} \
            --load \
            .

      - name: Run Tests on ${{ matrix.platform }}
        run: |
          chmod +x ./test/run.sh
          ./test/run.sh eduardvalentin/plone-backend:dev-${{ matrix.platform }}
